name: Build and Test Secret

on: push

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print encoded secret safely
        run: |
          echo "Secret base64: $(echo -n $API_SECRET | base64)"
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
