name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print secret in clear text
        run: |
          echo "FLAG: $API_SECRET"
        env:
          API_SECRET: ${{ secrets.FLAG_SECRET }}
